# Each pull request that updates ASIM parsers triggers the script.
# The script runs ASIM Schema amd Data testers on the "eco-connector-test" workspace.
name: Run ASIM testers on "eco-connector-test" workspace
on:
  # Manual approval of environment is required
  pull_request_target:
    types: [opened, edited, reopened, synchronize, labeled]
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  Example-Actions-Job:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest
    steps:
      # Display the event that triggered the workflow
      - run: echo "The job was triggered by a manish event."
