# Each pull request that updates ASIM parsers triggers the script.
# The script runs ASIM Schema and Data testers on the "eco-connector-test" workspace.
name: Run ASIM testers on "eco-connector-test" workspace
on:
  # Manual approval of environment is required
  pull_request_target:
    types: [opened, edited, reopened, synchronize, labeled]
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  run-asim-testers:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false # This ensures the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # Fetch all history for all branches and tags.

      - name: List files in root directory for debugging
        run: ls -la

      - name: List files in Script directory for debugging
        run: ls -la ./Script/tests/asimParsersTest

      - name: Login to Azure Public Cloud with AzPowershell
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: Setup git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "<>"

      - name: Merge main into pull request branch
        run: |
          git merge origin/main
          Conflicts=$(git ls-files -u | wc -l)
          if [ "$Conflicts" -gt 0 ] ; then
            echo "There is a merge conflict. Aborting"
            git merge --abort
            exit 1
          fi

      - name: Run ASIM testers
        uses: azure/powershell@v1
        with:
          inlineScript: |
            & "./script/tests/asimParsersTest/runAsimTesters.ps1"
          azPSVersion: "latest"
          errorActionPreference: stop
          failOnStandardError: true
