# Each pull request that updates ASIM parsers triggers the script.
# The script runs ASIM Schema and Data testers on the "eco-connector-test" workspace.
name: Run ASIM testers on "eco-connector-test" workspace
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, labeled]
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  run-asim-testers:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false
          fetch-depth: 0

      - name: Install latest Az module
        run: |
          pwsh -Command "Install-Module -Name Az -Force -AllowClobber"
          pwsh -Command "Update-Module -Name Az -Force"
      
      - name: Login to Azure Public Cloud with AzPowershell
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: Setup git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "<>"

      - name: Merge main into pull request branch
        run: |
          git merge origin/main
          Conflicts=$(git ls-files -u | wc -l)
          if [ "$Conflicts" -gt 0 ] ; then
            echo "There is a merge conflict. Aborting"
            git merge --abort
            exit 1

      - name: Run ASIM testers
        uses: azure/powershell@v2
        with:
          inlineScript: |
            & ".script/tests/asimParserTest/runAsimTesters.ps1"
          azPSVersion: "latest"
          errorActionPreference: stop
          failOnStandardError: true
